name: Trunk build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-clojure
      - run: make test
        shell: bash
  generate-docs:
    runs-on: ubuntu-latest
    needs: [ test ]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-clojure
      - run: |
          make codox
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to documentation detected."
          else
            git commit -m "Rebuilt documentation."
            git push origin main
          fi
        shell: bash
