name: Trunk build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-clojure
      - run: make build
        shell: bash
      - run: make test
        shell: bash
